### ISSUE TITLE
Acrescentar um .gitignore no seu repositório

### ISSUE THREAD

**Issue by marcelo-trier** [Hardtalinne/project-aula-java#1]
Aline, 
Verifique se na raiz do seu repositório tem um arquivo chamado .gitignore

Este gitignore serve para ignorar alguns arquivos do seu projeto que não precisam ser salvos aqui no seu controle de versões, como por exemplo os aquivos: .class

Veja exemplos na internet, converse comigo sobre o que encontrou e depois acrescente aqui no seu repositório de código. Depois disso remova o diretório out/* pois são apenas arquivos compilados e não precisam de versionamento.

**Comment by Hardtalinne** [comment]
Perfeito! Acabei esquecendo de colocar o arquivo .gitignore, já ajustei! Obrigada pelo feedback
